sos/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('sosapp.urls')),
    #url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
]

#urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sosapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'sos'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^chat/$', views.chatIndex, name='chatIndex'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^report_once/$',views.report_once, name='report_once'),
    url(r'^i_experienced/$', views.i_experienced, name='i_experienced'),
    url(r'^eduction/$',views.education,name='education'),
    url(r'^exp_stories/$', views.exp_stories, name='exp_stories'),
    url(r'^rep_stories/$', views.rep_stories, name='rep_stories'),
    url(r'^story/(?P<id>\d+)/$', views.story, name ='story'),
]

sosapp/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.validators import RegexValidator
from tinymce.models import HTMLField
from django.contrib.auth.models import User


class NonUserContactModel(models.Model):
    name = models.CharField(max_length=120, blank=False)
    email = models.EmailField(max_length=254, blank=False)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone = models.CharField(validators=[phone_regex],max_length=15 ,blank=False)
    message = models.TextField(blank=False)

    def __str__(self):
        return self.name


class ReportOnceModel(models.Model):
	r_user = models.ForeignKey(User)
	title = models.CharField(max_length=250,blank=False)
	details = HTMLField()
	r_created = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ('-r_created',)

	def __str__(self):
		return self.r_title

class IExperienceModel(models.Model):
	i_user = models.ForeignKey(User)
	title = models.CharField(max_length=250,blank=False)
	details = HTMLField()
	i_created = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ('-i_created',)

	def __str__(self):
		return self.i_title

class ProfileModel(models.Model):
	GENDER_CHOICES = (
		('female','Female'),
		('male','Male'),
	)
	user = models.OneToOneField(User)
	gender = models.CharField(max_length=25, blank=True, choices=GENDER_CHOICES, default='male')
	birthdate = models.DateField(blank=True, null=True)
	mobile = models.CharField(max_length=12, blank=True)
	address = models.CharField(max_length=500, blank=True)
	p_title = models.CharField(max_length=150, blank=True)
	p_company = models.CharField(max_length=150, blank=True)
	p_city = models.CharField(max_length=150, blank=True)
	p_time_from = models.DateField(blank=True, null=True)
	p_time_to = models.DateField(blank=True, null=True)

	def __str__(self):
		return self.user.username

sosapp/forms.py
from django import forms
from .models import NonUserContactModel, ReportOnceModel, IExperienceModel, ProfileModel
from tinymce.widgets import TinyMCE
from django.contrib.auth.models import User
from django.conf import settings

class NonUserContactForm(forms.ModelForm):
    class Meta:
        model = NonUserContactModel
        fields = '__all__'


class ReportOnceForm(forms.ModelForm):
	class Meta:
		model = ReportOnceModel
		fields = ['title', 'details']

class IExperienceForm(forms.ModelForm):
	class Meta:
		model = IExperienceModel
		fields = ['title', 'details']


# Edit Profile Forms (5)
class ProfileOverviewForm(forms.ModelForm):
	# birthdate = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)

	class Meta:
		model = ProfileModel
		fields = ['gender','birthdate']

class UserOverviewForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['first_name','last_name']

class ProfileContactForm(forms.ModelForm):
	class Meta:
		model = ProfileModel
		fields = ['mobile','address']

class UserContactForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['email']

class ProfileProfessionalForm(forms.ModelForm):
	class Meta:
		model = ProfileModel
		fields = ['p_title','p_company','p_city','p_time_from','p_time_to']

sosapp/views.py
import json
from django.shortcuts import render, redirect
from django.contrib import auth
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .forms import NonUserContactForm, ReportOnceForm, IExperienceForm, ProfileOverviewForm, \
                    UserOverviewForm, ProfileContactForm, UserContactForm, ProfileProfessionalForm
from utils import send_twilio_message
from .models import ProfileModel
from django.core.urlresolvers import reverse
from .models import ReportOnceModel, IExperienceModel
from django.shortcuts import get_object_or_404

def index( request ):
    if request.method == 'POST':
    	return contactUsSaveService( request );
    return render(request,'sosapp/index-default.html',{"contact_form":None})

def contactUsSaveService( request ):
    contact_form = NonUserContactForm( request.POST or None )
    if contact_form.is_valid():
        contact_form.save()
        return JsonResponse({ "status": 1, "message" : "Thank you! We will connect to you soon !" })
    return JsonResponse({ "status": 0, "message": "422 Unprocessable Entity", "errors" : []  },status=422)

@login_required
def logout( request ):
	auth.logout(request)
	return HttpResponseRedirect('/')


@login_required
def profile( request ):
    try:
        puser = ProfileModel.objects.get(user=request.user)
    except:
        puser = ProfileModel.objects.create(user=request.user)

    if request.method == 'POST':
        p_overform = ProfileOverviewForm(data=request.POST, instance=request.user.profilemodel)
        u_overform = UserOverviewForm(data=request.POST, instance=request.user)
        p_contactform = ProfileContactForm(data=request.POST, instance=request.user.profilemodel)
        u_contactform = UserContactForm(data=request.POST, instance=request.user)
        p_pform = ProfileProfessionalForm(data=request.POST, instance=request.user.profilemodel)
        if p_overform.is_valid() and u_overform.is_valid() and p_contactform.is_valid() \
            and u_contactform.is_valid() and p_pform.is_valid():
                p_overform.save()
                u_overform.save()
                p_contactform.save()
                u_contactform.save()
                p_pform.save()
                msg = 'Profile updated Successfully'
                return HttpResponseRedirect('/profile/')
        else:
            print "Errors"
            print p_overform.errors
            print u_overform.errors
            print p_contactform.errors
            print u_contactform.errors
            print p_pform.errors
    else:
        p_overform = ProfileOverviewForm(instance=request.user.profilemodel)
        u_overform = UserOverviewForm(instance=request.user)
        p_contactform = ProfileContactForm(instance=request.user.profilemodel)
        u_contactform = UserContactForm(instance=request.user)
        p_pform = ProfileProfessionalForm(instance=request.user.profilemodel)
    context = {'p_overform':p_overform, 'u_overform':u_overform, 'p_contactform':p_contactform,
               'u_contactform':u_contactform, 'p_pform':p_pform }
    return render(request,'sosapp/profile.html', context)


@login_required
def report_once(request):
    r_form = ReportOnceForm(request.POST or None)
    if r_form.is_valid():
        tmp = r_form.save(commit=False)
        tmp.r_user = request.user
        r_form.save()
        body = 'Hi {0}! Thanks For Your Story.'.format(request.user)
        sent = send_twilio_message('+917597004257',body)
        #print sent.sid
        # Imporvement Needed!
        return redirect('sos:index')
    return render(request,'sosapp/report_once.html',{'form':r_form})

@login_required
def i_experienced(request):
    i_form = IExperienceForm(request.POST or None)
    if i_form.is_valid():
        tmp = i_form.save(commit=False)
        tmp.i_user = request.user
        i_form.save()
        body = 'Hi {0}! Thanks For Your Story.'.format(request.user)
        sent = send_twilio_message('+917597004257',body)
        #print sent.sid
        # Imporvement Needed!
        return redirect('sos:index')
    return render(request,'sosapp/i_experienced.html',{'form':i_form})

def chatIndex(request):
    return render(request,'sosapp/firechat/index.html')

def education(request):
    return render(request, 'sosapp/blog-single.html')

@login_required
def exp_stories(request):
    exp_stories = IExperienceModel.objects.all()
    return render(request,'sosapp/all_stories.html',{'stories':exp_stories})

@login_required
def rep_stories(request):
    rep_stories = ReportOnceModel.objects.all()
    return render(request,'sosapp/all_stories.html',{'stories':rep_stories})

@login_required
def story(request,id):
    try:
        story = get_object_or_404(IExperienceModel, id=id)
    except:
        story = get_object_or_404(ReportOnceModel, id=id)
    return render(request,'sosapp/story.html',{'story':story})

templates/sosapp/all_stories.html
<!DOCTYPE html>
{% load staticfiles %}
{% load sos_tags %}
<html>
<head>
	<title>Test</title>
</head>
<body>
{% for item in stories %}
	TITLE:-
	<a href="{% url 'sos:story' id=item.id %}">{{ item.title }}</a><br /><br />
	BODY:-
	{{ item.details| markdown | truncatewords_html:30 }}
	<hr />
	<a href="{% url 'sos:story' id=item.id %}">Read Full</a>
	<hr />
{% endfor %}


</body>
</html>

templates/sosapp/i_experienced.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Test</title>
	<!--Tinymce Text-Editor (Must be in Head Tag) -->
  <script src="{% static 'sosapp/assets/js/tinymce/tinymce.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'sosapp/assets/js/tinymce/custom.js' %}" ></script>
  <!-- selector:textarea-tinymce -->
</head>
<body>
<form action=""  method="post" >

	{% csrf_token %}
<tr>
  <th><label for="id_details">Share Your Experience</label></th><br /><br />
  <th><label for="id_title">Title:</label></th>
  <td>
    <input id="id_title" maxlength="250" name="title" type="text" />
  </td>
</tr>
<br /><br />
<tr>

  <td>
    <textarea class="tinymce" cols="40" data-mce-conf="{&quot;relative_urls&quot;: false, &quot;spellchecker_languages&quot;: &quot;Afrikaans=af,Arabic=ar,Asturian=as,Azerbaijani=az,Bulgarian=bg,Belarusian=be,Bengali=bn,Breton=br,Bosnian=bs,Catalan=ca,Czech=cs,Welsh=cy,Danish=da,German=de,Greek=el,+English / Australian English / British English=en,Esperanto=eo,Spanish / Argentinian Spanish / Colombian Spanish / Mexican Spanish / Nicaraguan Spanish / Venezuelan Spanish=es,Estonian=et,Basque=eu,Persian=fa,Finnish=fi,French=fr,Frisian=fy,Irish=ga,Scottish Gaelic=gd,Galician=gl,Hebrew=he,Hindi=hi,Croatian=hr,Hungarian=hu,Interlingua=ia,Indonesian=id,Ido=io,Icelandic=is,Italian=it,Japanese=ja,Georgian=ka,Kazakh=kk,Khmer=km,Kannada=kn,Korean=ko,Luxembourgish=lb,Lithuanian=lt,Latvian=lv,Macedonian=mk,Malayalam=ml,Mongolian=mn,Marathi=mr,Burmese=my,Norwegian Bokmal=nb,Nepali=ne,Dutch=nl,Norwegian Nynorsk=nn,Ossetic=os,Punjabi=pa,Polish=pl,Portuguese / Brazilian Portuguese=pt,Romanian=ro,Russian=ru,Slovak=sk,Slovenian=sl,Albanian=sq,Serbian / Serbian Latin=sr,Swedish=sv,Swahili=sw,Tamil=ta,Telugu=te,Thai=th,Turkish=tr,Tatar=tt,Udmurt=ud,Ukrainian=uk,Urdu=ur,Vietnamese=vi,Simplified Chinese / Traditional Chinese=zh&quot;, &quot;theme&quot;: &quot;simple&quot;, &quot;strict_loading_mode&quot;: 1, &quot;mode&quot;: &quot;exact&quot;, &quot;language&quot;: &quot;en&quot;, &quot;elements&quot;: &quot;id_details&quot;, &quot;directionality&quot;: &quot;ltr&quot;}" id="id_details" name="details" rows="10">

  <p style="text-align: center; font-size: 15px;"><img title="TinyMCE Logo" src="//www.tinymce.com/images/glyph-tinymce@2x.png" alt="TinyMCE Logo" width="110" height="97" />
  </p>
  <h1 style="text-align: center;">Welcome to the TinyMCE & Community Plugins demo!</h1>
  <h5 style="text-align: center;">Note, this is not an "enterprise/premium" demo.<br>Visit the <a href="https://www.tinymce.com/pricing/#demo-enterprise">pricing page</a> to demo our premium plugins.</h5>
  <p>Please try out the features provided in this full featured example.</p>
  <p>Note that any <b>MoxieManager</b> file and image management functionality in this example is part of our commercial offering – the demo is to show the integration.</h2>

  <h2>Got questions or need help?</h2>
  <ul>
    <li>Our <a href="//www.tinymce.com/docs/">documentation</a> is a great resource for learning how to configure TinyMCE.</li>
    <li>Have a specific question? Visit the <a href="http://community.tinymce.com/forum/">Community Forum</a>.</li>
    <li>We also offer enterprise grade support as part of <a href="http://tinymce.com/pricing">TinyMCE Enterprise</a>.</li>
  </ul>

  <h2>A simple table to play with</h2>
  <table style="text-align: center;">
    <thead>
      <tr>
        <th>Product</th>
        <th>Cost</th>
        <th>Really?</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>TinyMCE</td>
        <td>Free</td>
        <td>YES!</td>
      </tr>
      <tr>
        <td>Plupload</td>
        <td>Free</td>
        <td>YES!</td>
      </tr>
    </tbody>
  </table>

  <h2>Found a bug?</h2>
  <p>If you think you have found a bug please create an issue on the <a href="https://github.com/tinymce/tinymce/issues">GitHub repo</a> to report it to the developers.</p>

  <h2>Finally ...</h2>
  <p>Don't forget to check out our other product <a href="http://www.plupload.com" target="_blank">Plupload</a>, your ultimate upload solution featuring HTML5 upload support.</p>
  <p>Thanks for supporting TinyMCE! We hope it helps you and your users create great content.<br>All the best from the TinyMCE team.</p>



  </textarea>
  </td>
  </tr>


	<input type="submit" value="Submit" />
</form>

</body>
</html>

templates/sosapp/report_once.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Test</title>
	<!--Tinymce Text-Editor (Must be in Head Tag) -->
  <script src="{% static 'sosapp/assets/js/tinymce/tinymce.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'sosapp/assets/js/tinymce/custom.js' %}" ></script>
  <!-- selector:textarea-tinymce -->
</head>
<body>
<form action=""  method="post" >
	{% csrf_token %}
<tr>
  <th><label for="id_details">Report Once</label></th><br /><br />
  <th><label for="id_title">Title:</label></th>
  <td><input id="id_title" maxlength="250" name="title" type="text" /></td>
</tr>
<br /><br />
  <tr>

    <td>
      <textarea class="tinymce" cols="40" data-mce-conf="{&quot;relative_urls&quot;: false, &quot;spellchecker_languages&quot;: &quot;Afrikaans=af,Arabic=ar,Asturian=as,Azerbaijani=az,Bulgarian=bg,Belarusian=be,Bengali=bn,Breton=br,Bosnian=bs,Catalan=ca,Czech=cs,Welsh=cy,Danish=da,German=de,Greek=el,+English / Australian English / British English=en,Esperanto=eo,Spanish / Argentinian Spanish / Colombian Spanish / Mexican Spanish / Nicaraguan Spanish / Venezuelan Spanish=es,Estonian=et,Basque=eu,Persian=fa,Finnish=fi,French=fr,Frisian=fy,Irish=ga,Scottish Gaelic=gd,Galician=gl,Hebrew=he,Hindi=hi,Croatian=hr,Hungarian=hu,Interlingua=ia,Indonesian=id,Ido=io,Icelandic=is,Italian=it,Japanese=ja,Georgian=ka,Kazakh=kk,Khmer=km,Kannada=kn,Korean=ko,Luxembourgish=lb,Lithuanian=lt,Latvian=lv,Macedonian=mk,Malayalam=ml,Mongolian=mn,Marathi=mr,Burmese=my,Norwegian Bokmal=nb,Nepali=ne,Dutch=nl,Norwegian Nynorsk=nn,Ossetic=os,Punjabi=pa,Polish=pl,Portuguese / Brazilian Portuguese=pt,Romanian=ro,Russian=ru,Slovak=sk,Slovenian=sl,Albanian=sq,Serbian / Serbian Latin=sr,Swedish=sv,Swahili=sw,Tamil=ta,Telugu=te,Thai=th,Turkish=tr,Tatar=tt,Udmurt=ud,Ukrainian=uk,Urdu=ur,Vietnamese=vi,Simplified Chinese / Traditional Chinese=zh&quot;, &quot;theme&quot;: &quot;simple&quot;, &quot;strict_loading_mode&quot;: 1, &quot;mode&quot;: &quot;exact&quot;, &quot;language&quot;: &quot;en&quot;, &quot;elements&quot;: &quot;id_details&quot;, &quot;directionality&quot;: &quot;ltr&quot;}" id="id_details" name="details" rows="10">


      <p style="text-align: center; font-size: 15px;"><img title="TinyMCE Logo" src="//www.tinymce.com/images/glyph-tinymce@2x.png" alt="TinyMCE Logo" width="110" height="97" />
  </p>
  <h1 style="text-align: center;">Welcome to the TinyMCE & Community Plugins demo!</h1>
  <h5 style="text-align: center;">Note, this is not an "enterprise/premium" demo.<br>Visit the <a href="https://www.tinymce.com/pricing/#demo-enterprise">pricing page</a> to demo our premium plugins.</h5>
  <p>Please try out the features provided in this full featured example.</p>
  <p>Note that any <b>MoxieManager</b> file and image management functionality in this example is part of our commercial offering – the demo is to show the integration.</h2>

  <h2>Got questions or need help?</h2>
  <ul>
    <li>Our <a href="//www.tinymce.com/docs/">documentation</a> is a great resource for learning how to configure TinyMCE.</li>
    <li>Have a specific question? Visit the <a href="http://community.tinymce.com/forum/">Community Forum</a>.</li>
    <li>We also offer enterprise grade support as part of <a href="http://tinymce.com/pricing">TinyMCE Enterprise</a>.</li>
  </ul>

  <h2>A simple table to play with</h2>
  <table style="text-align: center;">
    <thead>
      <tr>
        <th>Product</th>
        <th>Cost</th>
        <th>Really?</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>TinyMCE</td>
        <td>Free</td>
        <td>YES!</td>
      </tr>
      <tr>
        <td>Plupload</td>
        <td>Free</td>
        <td>YES!</td>
      </tr>
    </tbody>
  </table>

  <h2>Found a bug?</h2>
  <p>If you think you have found a bug please create an issue on the <a href="https://github.com/tinymce/tinymce/issues">GitHub repo</a> to report it to the developers.</p>

  <h2>Finally ...</h2>
  <p>Don't forget to check out our other product <a href="http://www.plupload.com" target="_blank">Plupload</a>, your ultimate upload solution featuring HTML5 upload support.</p>
  <p>Thanks for supporting TinyMCE! We hope it helps you and your users create great content.<br>All the best from the TinyMCE team.</p>


      </textarea>
    </td>
  </tr>

	<input type="submit" value="Submit" />
</form>
</body>
</html>

templates/sosapp/story.html
<!DOCTYPE html>
{% load staticfiles %}
{% load sos_tags %}
<html>
<head>
	<title>Test</title>
</head>
<body>
	TITLE:-
	{{ story.title }}<br /><br />
	<hr /><hr />
	BODY:-
	{{ story.details| markdown }}



</body>
</html>